[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -q
filterwarnings =
    ignore:datetime.datetime.utcnow.*:DeprecationWarning
    ignore:The Query.get\(\) method is considered legacy.*:sqlalchemy.exc.LegacyAPIWarning
